# icon matches Font Awesome icon name http://fontawesome.io/icons/#brand

github:
  icon: github
  network: Github
  username: arogachev
  url: https://github.com/arogachev
stackoverflow:
  icon: stack-overflow
  network: Stack Overflow
  username: arogachev
  url: http://stackoverflow.com/users/4323648/arogachev
linkedin:
  icon: linkedin
  network: LinkedIn
  username: Alexey Rogachev
  url: https://www.linkedin.com/in/alexey-rogachev-182b68109?trk=hp-identity-name
twitter:
  icon: twitter
  network: Twitter
  username: arogachev90
  url: https://twitter.com/arogachev90
facebook:
  icon: facebook
  network: Facebook
  username: Alexey Rogachev
  url: https://www.facebook.com/profile.php?id=100009774254444
instagram:
  icon: instagram
  network: Instagram
  username: arogachev90
  url: https://www.instagram.com/arogachev90/
